title = "The Things Stack for LoRaWAN"

baseURL = "http://localhost/"

disableKinds = [
  "taxonomy",
  "taxonomyTerm",
  "RSS",
  "sitemap",
]

enableGitInfo = true

languageCode = "en-us"
languageName = "English"

theme = "the-things-stack"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "The Things Stack for LoRaWAN"
  keywords = []
  github_repository = "https://github.com/TheThingsIndustries/lorawan-stack-docs"
  github_repository_edit = "https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/content"
  version = "v3.10"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.contributing]]
    name = "GitHub"
    url = "https://github.com/TheThingsIndustries/lorawan-stack-docs"
    weight = 1

  [[menu.contributing]]
    name = "Forum"
    url = "https://www.thethingsnetwork.org/forum/c/network-and-routing/v3"
    weight = 2

  [[menu.about_us]]
    name = "The Things Network"
    url = "https://www.thethingsnetwork.org"
    weight = 1

  [[menu.about_us]]
    name = "The Things Industries"
    url = "https://www.thethingsindustries.com"
    weight = 2
